- name: Run rpi-eeprom-update
  command: rpi-eeprom-update -a
  become: true
  register: eeprom_update

- name: Mark reboot needed if EEPROM update applied
  set_fact:
    reboot_needed: true
  when: eeprom_update.rc == 0 and ("bootloader update pending" in (eeprom_update.stdout | lower))
