- name: Read token from local file
  slurp:
    src: './../artifacts/k3s_node_token.txt'
  delegate_to: localhost
  register: token_raw

- name: Set k3s token and API URL facts
  set_fact:
    k3s_token: '{{ token_raw.content | b64decode | trim }}'
    k3s_url: "https://{{ hostvars[groups['control_plane'][0]].ansible_host }}:6443"
  when: token_raw.content is defined
