- name: Set system hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'
  become: true

- name: Ensure /etc/hosts has correct hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: '127.0.1.1 {{ inventory_hostname }}'
  become: true
