- name: Generate locale de_AT.UTF-8
  locale_gen:
    name: de_AT.UTF-8
    state: present

- name: Set LANG to de_AT.UTF-8
  lineinfile:
    path: /etc/default/locale
    regexp: '^LANG='
    line: 'LANG=de_AT.UTF-8'
    create: yes

- name: Set LC_ALL to de_AT.UTF-8
  lineinfile:
    path: /etc/default/locale
    regexp: '^LC_ALL='
    line: 'LC_ALL=de_AT.UTF-8'
    create: yes
